name: Release
on:
  workflow_dispatch: {}
env:
  BIN_NAME: type_buddy
  PROJECT_NAME: typeBuddy
  REPO_NAME: MitchWijt/typeBuddy
jobs:
  create-binaries:
    name: Create & Test Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build: [x86_64-linux, x86_64-macos]
        include:
          - build: x86_64-linux
            os: ubuntu-20.04
            rust: stable
            target: x86_64-unknown-linux-gnu
            cross: false

          - build: x86_64-macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            cross: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: test
          args: --release --locked --target ${{ matrix.target }}
          
      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked --target ${{ matrix.target }}
      - name: Rename release binary
        shell: bash
        run: mv target/${{ matrix.target }}/release/type_buddy target/${{ matrix.target }}/release/type_buddy-${{ matrix.target }}
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: target/${{ matrix.target }}/release/type_buddy-${{ matrix.target }}
  publish:
    name: Publish
    needs: [create-binaries]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/download-artifact@v3
        with:
          path: artifact

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "artifact/type_buddy-x86_64-unknown-linux-gnu, artifact/type_buddy-x86_64-apple-darwin"
